language: c
git:
  submodules: true
sudo: required
services: docker
env:
  global:
    - IMAGE_NAME=vasyahuyasa/remod

before_install:
  - sudo apt-get update
  - sudo apt-get install -y automake build-essential zlib1g-dev
 
compiler:
  - gcc

script:
  - cd src && make && make clean

before_deploy:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - cd ..
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
  - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
  - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${TRAVIS_TAG}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    branch: docker
